FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o notification_service ./cmd/notification

FROM alpine:3.18
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/notification_service .
COPY --from=builder /app/.env* ./
RUN adduser -D -g '' appuser
RUN chown -R appuser:appuser /app
USER appuser
CMD ["./notification_service"]
